name: Build and Release Extension

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Build Chrome extension
      run: |
        echo "Building Chrome extension..."
        node build-chrome.js
        
    - name: Build Firefox extension
      run: |
        echo "Building Firefox extension..."
        node build-firefox.js
        
    - name: Install web-ext for Firefox signing
      run: npm install --global web-ext
        
    - name: Sign Firefox extension
      run: |
        mkdir -p dist
        # Create unsigned ZIP first
        cd firefox && zip -r ../dist/shadowgag-firefox-${{ github.ref_name }}.zip . && cd ..
        # Sign the extension if API keys are available
        if [ -n "${{ secrets.AMO_JWT_ISSUER }}" ] && [ -n "${{ secrets.AMO_JWT_SECRET }}" ]; then
          echo "Signing Firefox extension..."
          web-ext sign --channel=unlisted --api-key="${{ secrets.AMO_JWT_ISSUER }}" --api-secret="${{ secrets.AMO_JWT_SECRET }}" --source-dir=firefox --artifacts-dir=dist
          # Rename the signed XPI to a more user-friendly name
          find dist -name "*.xpi" -exec mv {} dist/shadowgag-firefox-${{ github.ref_name }}-signed.xpi \;
        else
          echo "AMO API keys not found - skipping signing. Extension will be unsigned."
        fi
        
    - name: Create Chrome distribution package
      run: |
        cd chrome && zip -r ../dist/shadowgag-chrome-${{ github.ref_name }}.zip . && cd ..
        
    - name: Create source package
      run: |
        zip -r dist/shadowgag-source-${{ github.ref_name }}.zip \
          background.js \
          chrome/background-chrome.js \
          firefox/background-firefox.js \
          content.js \
          popup.html \
          popup.js \
          styles.css \
          package.json \
          README.md \
          LICENSE \
          CONTRIBUTING.md \
          SECURITY.md \
          FUNDING.md \
          PUBLISHING.md \
          .gitignore \
          build.js \
          build-chrome.js \
          build-firefox.js \
          icons/ \
          chrome/manifest.json \
          firefox/manifest.json
          
    - name: Generate checksums
      run: |
        cd dist
        sha256sum *.zip > checksums.txt
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          dist/shadowgag-chrome-${{ github.ref_name }}.zip
          dist/shadowgag-firefox-${{ github.ref_name }}.zip
          dist/shadowgag-firefox-${{ github.ref_name }}-signed.xpi
          dist/shadowgag-source-${{ github.ref_name }}.zip
          dist/checksums.txt
        body: |
          ## ShadowGag ${{ github.ref_name }}
          
          Browser extension that detects shadowbanned comments on 9gag.
          
          ### Downloads
          - **Chrome/Edge/Brave**: `shadowgag-chrome-${{ github.ref_name }}.zip`
          - **Firefox (Developer Mode)**: `shadowgag-firefox-${{ github.ref_name }}.zip`
          - **Firefox (Regular Users)**: `shadowgag-firefox-${{ github.ref_name }}-signed.xpi`
          - **Source Code**: `shadowgag-source-${{ github.ref_name }}.zip`
          
          ### Installation
          
          #### For Regular Firefox Users (Recommended):
          1. Download `shadowgag-firefox-${{ github.ref_name }}-signed.xpi`
          2. Open Firefox and go to `about:addons`
          3. Click the gear icon ⚙️ and select "Install Add-on From File"
          4. Select the downloaded `.xpi` file
          5. Click "Add" when prompted
          
          #### For Chrome/Edge/Brave Users:
          1. Download `shadowgag-chrome-${{ github.ref_name }}.zip`
          2. Extract the contents
          3. Open browser extensions page and enable "Developer mode"
          4. Click "Load unpacked" and select the extracted folder
          
          #### For Firefox Developers:
          1. Download `shadowgag-firefox-${{ github.ref_name }}.zip`
          2. Extract the contents
          3. Go to `about:debugging` → "This Firefox" → "Load Temporary Add-on"
          4. Select any file from the extracted folder
          
          See [README.md](https://github.com/shadowgagdev/shadowgag#installation) for detailed installation instructions.
          
          ### Support
          If you find this extension useful, consider supporting development:
          - **Ko-fi**: https://ko-fi.com/shadowgag
          
          ### Checksums
          SHA256 checksums are provided in `checksums.txt` for verification.
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 